language: groovy
sudo: false
jdk:
- openjdk17
branches:
  only:
  - master
  - develop
  - /^epic\/.*\/develop$/
  - /^feature.*$/
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
before_install:
- export TZ=Australia/Canberra
after_success:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && ./gradlew clean && travis_retry ./gradlew publish'
env:
  global:
  - JAVA_TOOL_OPTIONS=-Dhttps.protocols=TLSv1.2
  - secure: IknA5boEesNaWc8xKLC8pKk0Hl/B0FsNuBTvFHdJ6UbSUGlxMKT1NI/Ik0Ou/utewVbgLeNznQNhc261hYq3aCV5CHKc1e0IOD3bnEnTIfKUKvACmsy353HP9F8nOFwuRwlq/5BqgMdjr/TiK+oogxuw5C9KLZdwIaRoygA9Ho9kSvX6v47Eh3EPaIDGGdhNYOEzPfXSyNP8nAkHXD2amUxfK15Kxzb+cbfuTKfBDHd9iql1Z1evh1mctucYCVKVlaPdVF6N8duR/ZlJnrg7h+x+ANJR+HTrBQSFJlD/fpBnFAQZouTkZBn7P1suYX9Ja1DXUhnzlr7p8EgwavQC6dpbhVrnQMmeLT4Doa0VXsv0t81dYrSyDw6ELlgrmH2itOI27U04rn6GV8KjZyBigbXSKJml4XKXD3jJ4EN7B6yo4ZHEbFN5Fl/CUxHb7R4/EGg1wo8JWIQ6Bl5EBYmEa6JZm6592XS5Mv4t3DDqt89KS51FR1Ye9TcAUN0QzY4Y+IS3SEIe5WdhHng3V4ssYMXsmDHnoZryIn6QFKuMBSdlxeaF4Z/GMCzKxUPgit3PK2O+X62y9Av4D4qtrSBSNC67W4gMGTtW3+Wft5yEkpW4koftXB7wf1KPPMqFHOPX2u+M3WPDKUC7MLspPymKM+7Qv4LW/661okk4BTfX17I=
  - secure: rk5DfO3FzFm8r6CukcQ0gfoVHqy87zVAHgviHILMnlYHzuF+QfTK1x0k59o/fiRlQmBphfviJt+coGNK43tJceJYDIz/BhKbZew87UwHy4482ZcLzsRD/qtW0SU6LM0xXIGBQeRoBSiXSANVs0GZNfQDJm5OQDp0e8LYNSZ39icegHfZQBIngFWKvsBHiRRF5FeHiuq3VVJ4Jy7I1vB9LZBPE1QqJt2nDcFcCYjiYyqN6QGn3+W5fr/gUtpeNbR+cLMYiOmuIgZDX37lKMrAQLjdWZ9VSFyN6OfcVvyCuDxMQTFM3w7C0SUOoSwaQNQz9VZai1VWgcYXKuSv26IgqLiUagcJ2ijMR8IC6y0V7d2mphFNkb2mQ3m6zc/c/wNjpiayd51oIOupbsGvZVamHCgX3jnaaxnFLM2gc9qX1GMCsaOangfksbsPboIkkyRb7cUw9QlI6YNBbs7xdTnfeWcTlAYanRkSvi3DvuLDMrkvXBdCgXSLfQVBfHID7Ws+Wu2jP5fhgJwV2ANBB6qIU/8OpuE3vjlxmNJdUAO+Aq2fYSuN5HT9+BorG3wEqof8odjSvusWZId9rw+RURb6qKfoNL+4Ciqnisx26FN/fiocJGmvdSjOF8/togcv0kLzjPQfBIzXz6aHJabmvxkXLUfJy7T18w3RSUC/9o0uhJM=
