plugins {
    id 'groovy'
    id 'java-library'
    id 'maven-publish'
}

group "au.org.ala"
version = "3.0.0"
description = 'ALA Mail Library'

repositories {
    mavenCentral()
    maven { url "https://repo.grails.org/grails/core/" }
}

dependencies {
    api 'com.sun.mail:jakarta.mail:2.0.1'
    api 'software.amazon.awssdk:ses:2.40.8'
    implementation platform("org.apache.grails:grails-bom:${grailsVersion}")
    implementation 'org.apache.grails:grails-core'
    implementation 'org.springframework:spring-context-support'
    implementation 'org.springframework.boot:spring-boot-autoconfigure'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }

    withSourcesJar()
    withJavadocJar()
}

tasks.named('test') {
    useJUnitPlatform()
}

publishing {
    repositories {
        maven {
            name 'Nexus'
            url "https://nexus.ala.org.au/content/repositories/${project.version.endsWith('-SNAPSHOT') ? 'snapshots' : 'releases' }"
            credentials {
                username = System.getenv('TRAVIS_DEPLOY_USERNAME')
                password = System.getenv('TRAVIS_DEPLOY_PASSWORD')
            }
        }
    }
    publications {
        maven(MavenPublication) {
            artifactId = project.name
            from components.java

            pom {
                name = project.name
                description = 'Library to deliver mail via AWS SES'
                url = 'https://github.com/AtlasOfLivingAustralia/ala-mail'
                licenses {
                    license {
                        name = 'MPL-1.1'
                        url = 'https://www.mozilla.org/en-US/MPL/1.1/'
                    }
                }
                developers {
                }
                scm {
                    connection = 'scm:git:git://github.com/AtlasOfLivingAustralia/ala-mail.git'
                    developerConnection = 'scm:git:ssh://github.com:AtlasOfLivingAustralia/ala-mail.git'
                    url = 'https://github.com/AtlasOfLivingAustralia/ala-mail/tree/main'
                }
            }
        }
    }
}
